<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=2, viewport-fit=cover"
    />

    {{-- fonts --}}
    <link
        rel="preload"
        href="/fonts/Roboto/KFOlCnqEu92Fr1MmEU9fABc4AMP6lbBP.3e1bb90afe5eb4a94c5f.woff2"
        as="font"
        type="font/woff2"
        crossorigin
    >
    <link
        rel="preload"
        href="/fonts/Roboto/KFOmCnqEu92Fr1Mu72xKKTU1Kvnz.499af208fa04aa805317.woff2"
        as="font"
        type="font/woff2"
        crossorigin
    >
    <link
        rel="preload"
        href="/fonts/Roboto/KFOmCnqEu92Fr1Mu5mxKKTU1Kvnz.6b69287db14836e8ccee.woff2"
        as="font"
        type="font/woff2"
        crossorigin
    >
    <link
        rel="preload"
        href="/fonts/Roboto/KFOmCnqEu92Fr1Mu7mxKKTU1Kvnz.350ec982325895563ada.woff2"
        as="font"
        type="font/woff2"
        crossorigin
    >
    <link
        rel="preload"
        href="/fonts/Roboto/KFOmCnqEu92Fr1Mu4WxKKTU1Kvnz.af30acd9d70ade5b828d.woff2"
        as="font"
        type="font/woff2"
        crossorigin
    >
    <link
        rel="preload"
        href="/fonts/Roboto/KFOmCnqEu92Fr1Mu7WxKKTU1Kvnz.62afd8a72052ca925aaf.woff2"
        as="font"
        type="font/woff2"
        crossorigin
    >
    <link
        rel="preload"
        href="/fonts/Roboto/KFOmCnqEu92Fr1Mu7GxKKTU1Kvnz.009379f5feecd3ef689a.woff2"
        as="font"
        type="font/woff2"
        crossorigin
    >
    <link
        rel="preload"
        href="/fonts/Roboto/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.465390c6e54c60f4a15f.woff2"
        as="font"
        type="font/woff2"
        crossorigin
    >
    <link
        rel="preload"
        href="/fonts/Roboto/KFOlCnqEu92Fr1MmEU9fCRc4AMP6lbBP.66efaee062df58309edc.woff2"
        as="font"
        type="font/woff2"
        crossorigin
    >
    <link
        rel="preload"
        href="/fonts/Roboto/KFOlCnqEu92Fr1MmEU9fABc4AMP6lbBP.3e1bb90afe5eb4a94c5f.woff2"
        as="font"
        type="font/woff2"
        crossorigin
    >
    <link
        rel="preload"
        href="/fonts/Roboto/KFOlCnqEu92Fr1MmEU9fCBc4AMP6lbBP.acd64c8bf32762464b8f.woff2"
        as="font"
        type="font/woff2"
        crossorigin
    >
    <link
        rel="preload"
        href="/fonts/Roboto/KFOlCnqEu92Fr1MmEU9fBxc4AMP6lbBP.cab892ae9aa422233ea4.woff2"
        as="font"
        type="font/woff2"
        crossorigin
    >
    <link
        rel="preload"
        href="/fonts/Roboto/KFOlCnqEu92Fr1MmEU9fCxc4AMP6lbBP.01bafbfbc1e4ebe0139d.woff2"
        as="font"
        type="font/woff2"
        crossorigin
    >
    <link
        rel="preload"
        href="/fonts/Roboto/KFOlCnqEu92Fr1MmEU9fChc4AMP6lbBP.d3c211af53a789d2f9fd.woff2"
        as="font"
        type="font/woff2"
        crossorigin
    >
    <link
        rel="preload"
        href="/fonts/Roboto/KFOlCnqEu92Fr1MmEU9fBBc4AMP6lQ.324b1e6d0f5ae7c6ab42.woff2"
        as="font"
        type="font/woff2"
        crossorigin
    >
    {{-- fonts end --}}

    <title>Instagram</title>

    @vitereactrefresh
    @vite("resources/js/app.ts")
</head>
<body>
<div id="app"></div>
</body>
</html>
